version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    container_name: visionboard-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server/config.json:/app/config.json
      - backend_data:/app/focalboard.db
    depends_on:
      - db

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.frontend
    container_name: visionboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: visionboard-db
    restart: always
    environment:
      - POSTGRES_USER=visionboard
      - POSTGRES_PASSWORD=visionboard
      - POSTGRES_DB=visionboard
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  backend_data:
